### ISSUE TITLE
AttributeError: 'VideoKNetQuansiEmbedFCJointTrain' object has no attribute 'obj_feats_memory'

### ISSUE THREAD

**Issue by luoqianhao** [lxtGH/Video-K-Net#6]
when i run the command :  "CUDA_VISIBLE_DEVICES=6,7 bash ./tools/dist_step_test.sh configs/det/video_knet_vipseg/video_knet_s3_r50_rpn_vipseg_mask_embed_link_ffn_joint_train.py ./weights/video_k_net_r50_vip_seg.pth 2 --show-dir ./temp_output/", the error has happend. Detail information:
2023-03-14 11:11:13,824 - mmdet - INFO - VIPSegDVPSDataset : There are totally 343 videos in val split.
2023-03-14 11:11:14,362 - mmdet - INFO - VIPSegDVPSDataset : There are totally 8255 clips in val split for training.
load checkpoint from local path: ./weights/video_k_net_r50_vip_seg.pth
load checkpoint from local path: ./weights/video_k_net_r50_vip_seg.pth
load checkpoint from local path: ./weights/video_k_net_r50_vip_seg.pth
load checkpoint from local path: ./weights/video_k_net_r50_vip_seg.pth
The output dir is ./temp_output/
[                                                  ] 0/8255, elapsed: 0s, ETA:/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmdet/models/utils/positional_encoding.py:81: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature**(2 * (dim_t // 2) / self.num_feats)
fid 0
/home/user/luoqianhao/Video-K-Net-main/knet/video/kernel_iter_head.py:598: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  mask_indices = topk_indices // self.num_thing_classes
[                                                  ] 13/8255, 2.2 task/s, elapsed: 6s, ETA:  3784sThe output dir is ./temp_output/
[                                                  ] 0/8255, elapsed: 0s, ETA:The output dir is ./temp_output/
[                                                  ] 14/8255, 2.1 task/s, elapsed: 7s, ETA:  3943sfid 0
/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmdet/models/utils/positional_encoding.py:81: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature**(2 * (dim_t // 2) / self.num_feats)
Traceback (most recent call last):
  File "./tools/test_step.py", line 269, in <module>
    main()
  File "./tools/test_step.py", line 261, in main
    outputs, pred_pans_2ch = single_gpu_test(model, data_loader, args.show, args.show_dir,
  File "./tools/test_step.py", line 48, in single_gpu_test
    segm_results = model(return_loss=False, rescale=True, **data)
  File "/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/user/luoqianhao/Video-K-Net-main/knet/video/knet_quansi_dense_embed_fc_joint_train.py", line 520, in simple_test
    previous_obj_feats=self.obj_feats_memory,
  File "/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VideoKNetQuansiEmbedFCJointTrain' object has no attribute 'obj_feats_memory'
/home/user/anaconda3/envs/mmseg/lib/python3.8/site-packages/mmdet/models/utils/positional_encoding.py:81: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature**(2 * (dim_t // 2) / self.num_feats)
[                                                  ] 15/8255, 2.1 task/s, elapsed: 7s, ETA:  3899sTraceback (most recent call last):

**Comment by lxtGH** [comment]
It seems like a run time error. I see you use two GPUs. However, for VPS testing, we only support one GPU. Would you change it into one GPU?
