### ISSUE TITLE
ModuleNotFoundError: No module named 'external.mot_step'

### ISSUE THREAD

**Issue by kareem-metwaly** [lxtGH/Video-K-Net#8]
Hi,

Thank you for this great work. I was trying to train the network using the configurations in `configs/det/coco/knet_s3_r50_fpn_ms-3x_coco-panoptic.py` but I got an error as follows

```sh
Traceback (most recent call last):
  File "/opt/anaconda3/envs/vknet/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/opt/anaconda3/envs/vknet/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'external.mot_step'
````

It seems that there are missing files, could you upload them?  or let me know where I can find them

Thanks in advance.

**Comment by kareem-metwaly** [comment]
I fixed this by commenting the lines related to it in the configurations, apparently, it's not actually needed.
